# Generated by Django 5.2.5 on 2025-08-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(max_length=255)),
                ('processor', models.CharField(max_length=255)),
                ('number_of_cores', models.IntegerField()),
                ('number_of_threads', models.IntegerField()),
                ('ram_total_gb', models.FloatField()),
                ('ram_used_gb', models.FloatField()),
                ('ram_available_gb', models.FloatField()),
                ('storage_total_gb', models.FloatField()),
                ('storage_used_gb', models.FloatField()),
                ('storage_free_gb', models.FloatField()),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_details', to='monitor.snapshot')),
            ],
        ),
    ]
